backbone:
    name: ecmnet
    depths: [2,6,6,2]
    channels: [48,96,192,384,768] # five blocks
    outputs: [ "stage2", "stage3", "stage4" ]
    norm: bn
    act: silu

neck:
    name: al_pafpn
    depths: [2,2,2,2]
    channels: [192,384,768]
    norm: bn
    act: silu

head:
    name: decoupled_head
    num_anchor: 1
    channels: [192,384,768]
    norm: bn
    act: silu

loss:
    name: yolox
    stride: [8,16,32]

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
